# Cargo

# [[file:~/Workspace/Programming/structure-predication/kickstart/kickstart.note::*Cargo][Cargo:1]]
[package]
name = "kickstart"
version = "0.0.21"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
serde = {version="1.0", features = ["derive"]}
serde_json = "1.0"
indexmap = "1"
lazy_static = "1.3"
rand = "0.7"
warp = "0.1"
pager = "0.15"
tokio = "0.1"
tokio-signal = "0.2"
tokio-process = "0.2"
linefeed = "0.6"
structopt = "0.3"
toml = "0.5"
crossbeam-channel = "0.3"
signal-hook = "0.1"
#ctrlc = "3"
#-------------------------------------------------
gut = { version="0.1.2", package="gchemol-gut" }
gosh = { version = "0.0.25", features=["adhoc"] }
spdkit = { version="0.0.18" }
educate = { path = "../structure-education" }
# Cargo:1 ends here
