# cargo.toml

# [[file:~/Workspace/Programming/structure-predication/kickstart/kickstart.note::*cargo.toml][cargo.toml:1]]
[package]
name = "kickstart"
version = "0.0.19"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
rand = "0.7"
quicli = "0.4"
gosh = {path = "/home/ybyygu/Workspace/Programming/gosh-rs/gosh"}
#gosh = {git = "https://github.com/gosh-rs/gosh.git", tag="v0.0.22"}
gosh-db = {version = "*", path = "../../gosh-rs/database"}
crossbeam-channel = "0.3"
spdkit = { path = "../spdkit" }
#spdkit = { git = "https://github.com/spdkit/spdkit.git" }
indexmap = "1"
educate = { path = "../structure-education" }
structopt = "0.2"
serde = {version="1.0", features = ["derive"]}
serde_json = "1.0"
toml = "0.5"
lazy_static = "1.3"
# cargo.toml:1 ends here
