# cargo.toml

# [[file:~/Workspace/Programming/structure-predication/kickstart/kickstart.note::*cargo.toml][cargo.toml:1]]
[package]
name = "kickstart"
version = "0.0.5"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
rand = "0.6"
quicli = "0.4"
genevo = "0.4"
#gosh = {git = "https://github.com/gosh-rs/gosh.git", tag="v0.0.21"}
gosh = {path = "/home/ybyygu/Workspace/Programming/gosh-rs/gosh"}
#spdkit = { git = "https://github.com/spdkit/spdkit.git" }
spdkit = { path = "../spdkit" }
structopt = "0.2"
serde = "*"
toml = "*"
# cargo.toml:1 ends here
